### ISSUE TITLE
Научиться не считать и не показывать счетчики трансформаций

### ISSUE THREAD

**Issue by elephantum** [epoch8/datapipe-app#45]
Некоторые пайплайны содержат очень много данных и подсчет количества измененных индексов в трансформаци является очень медленной операцией. В этом случае интерфейс datapipe-app не может загрузиться.

Надо уметь отключать подсчет количества (возможно это должно быть режимом по умолчанию) чтобы можно было смотреть большие пайплайны.

**Comment by Sult1k** [comment]
Done
